import { Request, Response } from 'express';
import { ContractService } from '../services/contract.service.js';
import { validateContract } from '../utils/validators.js';
export class ContractController {
  private contractService=new ContractService();
  public getAll=async(_req:Request,res:Response):Promise<void>=>{try{res.json(await this.contractService.getAllContracts());}catch(error:any){res.status(500).json({message:error.message||'Error al obtener contratos.'});}};
  public getById=async(req:Request,res:Response):Promise<void>=>{try{const item=await this.contractService.getContractById(Number(req.params.id));if(!item){res.status(404).json({message:'Contrato no encontrado.'});return;}res.json(item);}catch(error:any){res.status(500).json({message:error.message||'Error al obtener contrato.'});}};
  public create=async(req:Request,res:Response):Promise<void>=>{try{const v=validateContract(req.body);if(!v.valid){res.status(400).json({message:'message' in v ? v.message : 'Datos inválidos'});return;}res.status(201).json({message:'Contrato registrado exitosamente.',contract:await this.contractService.createContract(req.body)});}catch(error:any){res.status(400).json({message:error.message||'Error al crear contrato.'});}};
  public updateStatus=async(req:Request,res:Response):Promise<void>=>{try{const v=validateContract({status:req.body.status},true);if(!v.valid){res.status(400).json({message:'message' in v ? v.message : 'Datos inválidos'});return;}const ok=await this.contractService.updateContractStatus(Number(req.params.id),req.body.status);if(!ok){res.status(404).json({message:'Contrato no encontrado.'});return;}res.json({message:'Estado del contrato actualizado correctamente.'});}catch(error:any){res.status(400).json({message:error.message||'Error al actualizar estado.'});}};
  public update=async(req:Request,res:Response):Promise<void>=>{try{const v=validateContract(req.body,true);if(!v.valid){res.status(400).json({message:'message' in v ? v.message : 'Datos inválidos'});return;}const ok=await this.contractService.updateContract(Number(req.params.id),req.body);if(!ok){res.status(404).json({message:'Contrato no encontrado.'});return;}res.json({message:'Contrato actualizado correctamente.'});}catch(error:any){res.status(400).json({message:error.message||'Error al actualizar contrato.'});}};
  public delete=async(req:Request,res:Response):Promise<void>=>{try{const ok=await this.contractService.deleteContract(Number(req.params.id));if(!ok){res.status(404).json({message:'Contrato no encontrado.'});return;}res.json({message:'Contrato eliminado correctamente.'});}catch(error:any){res.status(500).json({message:error.message||'Error al eliminar contrato.'});}};
}
